language: python

env:
      global:
        # Doctr deploy key for isilber/cld_INP_1D_model
        - secure: "i9MvoMyaISparWO5e0kb45NIRYpaiDJayxyzTqKs1kTNAm68PA7+3vDZomG+aQaElpUF2I07IW6LWwO1sqTQ0O6s9BPaoN1m+4Ygmc5tDxLHKk6kPzFj3dHigMPse+fWGJl8Nk1LvrW/ccNR8l7weWupsb6HsQirxIY7FQCDM7HH+nnYMgMQgxYhDzq9Oj4KKSa9rWtXgSxjeUSvyh3gji5FKXQdsWNVVmO/iaiN5cVNwkOIF57OETfyS8aHB3TQZNUGrwce8wFH2037CBgWyG1GFHlDcBJTcUd/PqXjIVVPQiqzEBnQ7yfxG/yqOV02QX7ewsRjKVi4n38DhFnpK7hK6DyigM1c5zFABYS3W63fw8iCyUJjN0D/9hv46EA61Jgvj6ITS1bid/If5eNjm6HX2JdoJESLMUjrLhTL7hT2ehzrzPIfnffVTUvHzEiNhn/lSbV00kThTtjBke30jw3ymYKi4LhwjDsbVLi4TcG812i2OK/t3iFQfjwF4roLdyZxukM9ILbGHKe1MKE2phG3ZxFtmMR2pZQZcU8AuNYRgzuW12CJETq0o58k1WDvUCbMC9wYxcRD1vxUcOjbNeZ5qNN2ypA56TY8cvNwiIjxxKbavyWposnVzxI47tQ/W67d51zBjiTuoOwJIMEEhU3s6lq/FNg0XLmiD3axkqE="

matrix:
    include:
    - python: 3.6
      env:
        - PYTHON_VERSION="3.6"
    - python: 3.7
      sudo: true
      dist: xenial
      env:
        - PYTHON_VERSION="3.7"
        - DOC_BUILD="true"
    - python: 3.8
      sudo: true
      dist: xenial
      env:
          - PYTHON_VERSION="3.8"
install:
    - source continuous_integration/install.sh

script:
    - source continuous_integration/build_docs.sh
    - flake8 --max-line-length=115 --ignore=F401,E402,W504,W605,E731

