language: python

env:
      global:
        # Deploy key
        - secure: "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACBv+3ogOLOlwrs4EabRoR3MquP2HpdyPsocQ08E30+z3wAAAKAMav0fDGr9HwAAAAtzc2gtZWQyNTUxOQAAACBv+3ogOLOlwrs4EabRoR3MquP2HpdyPsocQ08E30+z3wAAAEAP9eGw3U+I6wkDtbYislzBHwkN2t2CSZMOq2hE1CQiYW/7eiA4s6XCuzgRptGhHcyq4/Yel3I+yhxDTwTfT7PfAAAAF2lzcmFlbDBzaWxiZXJAZ21haWwuY29tAQIDBAUG"

matrix:
    include:
    - python: 3.7
      sudo: true
      dist: xenial
      env:
        - PYTHON_VERSION="3.7"
        - DOC_BUILD="true"
    - python: 3.8
      sudo: true
      dist: xenial
      env:
          - PYTHON_VERSION="3.8"
install:
    - source continuous_integration/install.sh

script:
    - source continuous_integration/build_docs.sh
    - flake8 --max-line-length=115 --ignore=F401,E402,W504,W605,E731

