language: python

matrix:
    include:
    - python: 3.7
      sudo: true
      dist: xenial
      env:
        - PYTHON_VERSION="3.7"
        - DOC_BUILD="true"
    - python: 3.8
      sudo: true
      dist: xenial
      env:
          - PYTHON_VERSION="3.8"

