name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - xarray
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - flake8
  - pint
  - sphinx
  - nbsphinx
  - numpydoc
  - pip:
    - sphinx_gallery
    - sphinx-copybutton
    - sphinx_rtd_theme
    - cloud_sptheme
