name: testenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - pytest-mpl
  - pytest-cov
  - dask
  - xarray
  - astral
  - flake8
  - ipython
  - metpy
  - pint=0.8.1
  - act-atmos
  - pip:
    - pymiescatt